#!/bin/bash
# Run the Paperclip background service from this local checkout.
#
# `paperclipai service install` normally points the service (a macOS
# LaunchAgent or a systemd user unit) at the managed shim in ~/.local/bin,
# which runs a published release. This script re-points it at the code in this
# folder instead — the same code `pnpm dev` runs, the same data directory
# (~/.paperclip/instances/<id>), with the UI served by the dev middleware.
# Re-run it after `git pull` to pick up new code and dependencies.
#
# What it does:
#   1. installs workspace dependencies (pnpm install), unless --skip-deps
#   2. writes a launcher that runs this checkout's CLI with node + tsx, and
#      carries over the current shell's PATH — a background service otherwise
#      starts with a minimal PATH and cannot find opencode, pi, hermes, ollama
#      or anything else under Homebrew or ~/.local/bin
#   3. uninstalls the existing service and installs it again with that
#      launcher (PAPERCLIP_SHIM_PATH), then waits for it to report healthy
#   4. records PAPERCLIP_SHIM_PATH in your shell profile, so later
#      `paperclipai service restart` keeps using the local launcher
#
# Usage:
#   scripts/service-from-local.sh [install] [--instance <id>] [--skip-deps]
#   scripts/service-from-local.sh status   [--instance <id>]
#   scripts/service-from-local.sh logs     [--instance <id>]
#   scripts/service-from-local.sh revert   [--instance <id>]   # back to the managed release
#
# Stop `pnpm dev` before installing: both serve the same port and data.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMMAND="install"
case "${1:-}" in
  install|status|logs|revert) COMMAND="$1"; shift ;;
  -h|--help) sed -n '2,29p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
esac
INSTANCE="default"
SKIP_DEPS=0
while [ $# -gt 0 ]; do
  case "$1" in
    --instance|-i) INSTANCE="$2"; shift 2 ;;
    --skip-deps) SKIP_DEPS=1; shift ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done
case "$INSTANCE" in
  ''|*[!A-Za-z0-9_-]*) echo "Instance ids use letters, digits, - and _ only: $INSTANCE" >&2; exit 2 ;;
esac

PAPERCLIP_HOME_DIR="${PAPERCLIP_HOME:-$HOME/.paperclip}"
LAUNCHER="$PAPERCLIP_HOME_DIR/bin/paperclipai-local-$INSTANCE"
PROFILE_BEGIN="# >>> paperclip local service ($INSTANCE) >>>"
PROFILE_END="# <<< paperclip local service ($INSTANCE) <<<"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok() { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }

shell_profile() {
  case "$(basename "${SHELL:-}")" in
    zsh) echo "$HOME/.zshrc" ;;
    bash) if [ "$(uname -s)" = "Darwin" ]; then echo "$HOME/.bash_profile"; else echo "$HOME/.bashrc"; fi ;;
    *) echo "$HOME/.profile" ;;
  esac
}

# Single-quote a value for a POSIX shell script.
shell_quote() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

# Run this checkout's CLI directly (it exists before the launcher does).
local_cli() {
  (cd "$REPO_ROOT" && node "$REPO_ROOT/cli/node_modules/tsx/dist/cli.mjs" "$REPO_ROOT/cli/src/index.ts" "$@")
}

remove_profile_block() {
  local profile="$1"
  [ -f "$profile" ] || return 0
  local tmp
  tmp="$(mktemp)"
  awk -v begin="$PROFILE_BEGIN" -v end="$PROFILE_END" '
    $0 == begin { skipping = 1; next }
    $0 == end { skipping = 0; next }
    !skipping { print }
  ' "$profile" >"$tmp"
  cat "$tmp" >"$profile"
  rm -f "$tmp"
}

cmd_install() {
  bold "Paperclip service from $REPO_ROOT (instance: $INSTANCE)"
  command -v node >/dev/null || { echo "node is not on PATH." >&2; exit 1; }
  command -v pnpm >/dev/null || { echo "pnpm is not on PATH (corepack enable pnpm)." >&2; exit 1; }
  [ -f "$REPO_ROOT/cli/src/index.ts" ] || { echo "Not a Paperclip checkout: $REPO_ROOT" >&2; exit 1; }

  if [ "$SKIP_DEPS" = 0 ]; then
    bold "Installing dependencies"
    (cd "$REPO_ROOT" && pnpm install)
  fi
  [ -f "$REPO_ROOT/cli/node_modules/tsx/dist/cli.mjs" ] || {
    echo "cli/node_modules/tsx is missing; run pnpm install first." >&2
    exit 1
  }

  bold "Writing the launcher"
  local node_bin
  node_bin="$(command -v node)"
  mkdir -p "$(dirname "$LAUNCHER")"
  cat >"$LAUNCHER" <<EOF
#!/bin/sh
# Generated by scripts/service-from-local.sh — runs Paperclip from a local checkout.
# Re-run that script after moving the checkout or changing Node versions.
export PATH=$(shell_quote "$PATH")
cd $(shell_quote "$REPO_ROOT") || exit 1
exec $(shell_quote "$node_bin") $(shell_quote "$REPO_ROOT/cli/node_modules/tsx/dist/cli.mjs") $(shell_quote "$REPO_ROOT/cli/src/index.ts") "\$@"
EOF
  chmod 755 "$LAUNCHER"
  ok "$LAUNCHER"

  bold "Reinstalling the service"
  if curl -fsS -m 2 "http://127.0.0.1:${PAPERCLIP_PORT:-3100}/api/health" >/dev/null 2>&1; then
    warn "Something already serves port ${PAPERCLIP_PORT:-3100}. If it is \`pnpm dev\`, stop it (Ctrl+C) — the service needs the port."
  fi
  PAPERCLIP_SHIM_PATH="$LAUNCHER" local_cli service uninstall --instance "$INSTANCE" >/dev/null 2>&1 || true
  local result
  result="$(PAPERCLIP_SHIM_PATH="$LAUNCHER" local_cli service install --instance "$INSTANCE" --json)"
  if printf '%s' "$result" | grep -q '"supported": false'; then
    echo "$result" >&2
    echo "This machine has no supported service manager (launchd or a systemd user session)." >&2
    exit 1
  fi
  ok "Installed: $(printf '%s' "$result" | awk -F'"' '/"definitionPath"/ { print $4 }')"

  bold "Remembering the launcher"
  local profile
  profile="$(shell_profile)"
  remove_profile_block "$profile"
  {
    echo "$PROFILE_BEGIN"
    echo "export PAPERCLIP_SHIM_PATH=$(shell_quote "$LAUNCHER")"
    echo "$PROFILE_END"
  } >>"$profile"
  ok "PAPERCLIP_SHIM_PATH set in $profile (open a new terminal to use it)"

  bold "Waiting for the service"
  local _
  for _ in $(seq 1 90); do
    if PAPERCLIP_SHIM_PATH="$LAUNCHER" local_cli service status --instance "$INSTANCE" --json 2>/dev/null \
      | grep -q '"ok": true'; then
      ok "Paperclip is running from this folder."
      echo "  Logs: scripts/service-from-local.sh logs"
      return 0
    fi
    sleep 2
  done
  warn "The service has not reported healthy yet. Check: scripts/service-from-local.sh logs"
  exit 1
}

cmd_revert() {
  bold "Returning instance $INSTANCE to the managed release"
  PAPERCLIP_SHIM_PATH="$LAUNCHER" local_cli service uninstall --instance "$INSTANCE" || true
  remove_profile_block "$(shell_profile)"
  rm -f "$LAUNCHER"
  ok "Removed the local launcher and the profile entry."
  echo "  Open a new terminal, then run: paperclipai install && paperclipai service install"
}

case "$COMMAND" in
  install) cmd_install ;;
  status) PAPERCLIP_SHIM_PATH="$LAUNCHER" local_cli service status --instance "$INSTANCE" ;;
  logs) PAPERCLIP_SHIM_PATH="$LAUNCHER" local_cli service logs --instance "$INSTANCE" --follow ;;
  revert) cmd_revert ;;
esac
